# Generated by Django 5.1.4 on 2025-01-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
