# Generated by Django 5.1.4 on 2025-01-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_reminder_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reminder',
            old_name='time',
            new_name='due_date',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='user',
        ),
        migrations.AddField(
            model_name='reminder',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
