# Generated by Django 5.1.4 on 2025-01-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_time_reminder_due_date_remove_reminder_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='due_time',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='due_date',
            field=models.DateField(),
        ),
    ]
