# Generated by Django 5.1.4 on 2025-03-09 15:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_reminder_due_time_alter_reminder_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='description',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='due_time',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='title',
        ),
        migrations.AddField(
            model_name='reminder',
            name='message',
            field=models.TextField(default='Default Reminder'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='scheduled_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
