# Generated by Django 5.1.4 on 2025-03-25 16:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_task_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reminder',
            old_name='scheduled_time',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='message',
        ),
        migrations.AddField(
            model_name='reminder',
            name='text',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
